### ISSUE TITLE
Possibilty training on another training set

### ISSUE THREAD

**Issue by shyranok** [The-Learning-And-Vision-Atelier-LAVA/DASR#70]
Hi,

I am highly interested in your work and code. I am trying to use another training dataset (SiblingsDB) to train your DASR model. However, when I tried to run the main.sh file for training after I changed the dir_data to my _data_path and put my dataset in my_data_path/DF2K/HR, the following error occurs in line 65 of multiscalesrdata.py: "self.repeat = args.test_every // (len(self.images_hr) // args.batch_size) ERROR: ZeroDivisionError: integer division or modulo by zero".

Do you know what the problem is?

Thank you in advance.

**Comment by FeiSong123** [comment]
same issue. Have you solved it ?

**Comment by shyranok** [comment]
Hi,

Yes I solved the problem. However, since I solved this almost 3 years ago I cannot remember anymore what the issue was. What I can do is share my code with you. 

Let me know if you are interested in the code.

**Comment by FeiSong123** [comment]
Thank you so much! I’m very interested in the code, and it would be great if you could send it to my email at xsong2008@126.com. I really appreciate your help!

**Comment by shyranok** [comment]
Hi,

Due to the large file size, I cannot share the entire code with you via email. I would suggest that you take a look at my repository at: https://github.com/shyranok/Thesis.git.

I hope this helps.

**Comment by FeiSong123** [comment]
Thanks.
